# Generated by Django 2.1.2 on 2018-10-10 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_format', models.CharField(help_text='Format of file', max_length=10)),
                ('file_size', models.IntegerField(help_text='Size of file in bytes')),
                ('compressor', models.CharField(help_text='Compressor programm', max_length=10)),
                ('compressor_password', models.CharField(help_text='password on file', max_length=30)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
    ]
