# Generated by Django 2.1.2 on 2018-10-10 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookItemPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of storage', max_length=10)),
                ('type', models.IntegerField(choices=[(2, 'General'), (3, 'Yandex'), (4, 'Google'), (5, 'RemoteStorage'), (1, 'Unknown')], default=1, help_text='Storage type')),
            ],
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='compressor',
            field=models.IntegerField(choices=[(1, 'Uncompressed'), (1, '7zip'), (3, 'rar'), (4, 'tgz')], default=1, help_text='Compressor type'),
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='file_format',
            field=models.CharField(help_text='Format of file pdf,djvu,doc,fb2...', max_length=10),
        ),
        migrations.AddField(
            model_name='bookitemplace',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.BookItem'),
        ),
        migrations.AddField(
            model_name='bookitemplace',
            name='storage_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Storage'),
        ),
    ]
