# Generated by Django 2.1.2 on 2018-10-14 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20181010_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='old_id',
            new_name='old',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ISBN',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='', help_text='ISBN', max_length=40),
        ),
        migrations.AddField(
            model_name='book',
            name='pages_count',
            field=models.IntegerField(default=0, help_text='number of pages'),
        ),
        migrations.AddField(
            model_name='storage',
            name='available',
            field=models.BooleanField(default=False, help_text='status of avaliable'),
        ),
        migrations.AddField(
            model_name='storage',
            name='last_accessable',
            field=models.DateTimeField(default=None, help_text='Last used timestamp'),
        ),
        migrations.AddField(
            model_name='storage',
            name='size',
            field=models.IntegerField(default=0, help_text='Size of storage in bytes'),
        ),
        migrations.AddField(
            model_name='storage',
            name='used',
            field=models.IntegerField(default=0, help_text='usage storage in bytes'),
        ),
        migrations.AlterField(
            model_name='book',
            name='inserted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
